/**
 * Technocore Contribution Evidence Vault — Formatting, Export & Import Engine
 *
 * Formats evidence into canonical JSON and Markdown reports with strict provenance notices.
 * Handles full import re-verification (schema -> payload -> signature -> integrity hash).
 */

import { computeEvidenceIntegrityHash, extractHashedFields } from "./integrity.ts";
import { validateEvidenceSchema } from "./schema.ts";
import type { ContributionEvidenceV1, EvidenceImportResult } from "./types.ts";
import { verifyEvidenceRecord } from "./verify.ts";

/**
 * Format evidence into a pretty-printed canonical JSON package.
 */
export function formatEvidenceJson(evidence: ContributionEvidenceV1): string {
  const fields = extractHashedFields(evidence);
  const full = {
    ...fields,
    capturedAt: evidence.capturedAt,
    verificationStatus: evidence.verificationStatus,
    evidenceSha256: evidence.evidenceSha256,
    notes: evidence.notes || undefined,
  };
  return JSON.stringify(full, null, 2);
}

/**
 * Generate a durable Markdown Evidence Report.
 */
export function formatEvidenceMarkdown(evidence: ContributionEvidenceV1): string {
  const isServerRetrieved = evidence.provenance === "SERVER_RETRIEVED";
  const provenanceLabel = isServerRetrieved
    ? "SERVER-RETRIEVED EVIDENCE"
    : "MANUALLY PROVIDED HISTORICAL RECORD";

  const verificationPill =
    evidence.verificationStatus === "VERIFIED"
      ? "✓ CRYPTOGRAPHICALLY VERIFIED"
      : evidence.verificationStatus === "INVALID_SIGNATURE"
        ? "✕ INVALID SIGNATURE"
        : "⚠ INSUFFICIENT EVIDENCE";

  return `# Technocore Contribution Evidence Report

> **Notice**: Locally preserved evidence of a Technocore signed record. Technocore room retention may change independently of this local copy.

---

### Contribution Overview
- **Topic**: ${evidence.topic || "Technocore Contribution"}
- **Contribution URL**: ${evidence.contributionUrl || "N/A"}
${evidence.projectName ? `- **Project Name**: ${evidence.projectName}\n` : ""}${evidence.gitCommit ? `- **Git Commit**: \`${evidence.gitCommit}\`\n` : ""}${evidence.xUrl ? `- **X (Twitter) URL**: ${evidence.xUrl}\n` : ""}
- **Captured At**: \`${evidence.capturedAt}\`
- **Provenance**: **${provenanceLabel}**

---

### Cryptographic Verification
- **Status**: **${verificationPill}**
- **Verification Method**: \`${evidence.verificationMethod}\`
- **Agent DID**: \`${evidence.did}\`
- **Room**: \`/r/${evidence.room}\`
- **Sequence Number**: \`${evidence.seq}\`
- **Server Timestamp**: \`${evidence.serverTimestamp}\`
- **Nonce**: \`${evidence.nonce}\`

---

### Wire Message & Canonical Payload
\`\`\`text
${evidence.text}
\`\`\`

- **Canonical Formula**: \`room|nonce|text\`
- **Canonical Wire Representation**:
\`\`\`text
${evidence.canonicalPayload}
\`\`\`
- **Payload SHA-256 Digest**: \`${evidence.canonicalPayloadSha256}\`
- **Signature (Base64URL, 86 chars)**:
\`\`\`text
${evidence.signature}
\`\`\`

---

### Evidence Integrity Package
- **Schema Version**: \`${evidence.schema}\`
- **Source Endpoint**: \`${evidence.sourceEndpoint}\`
- **Source Method**: \`${evidence.sourceMethod}\`
- **Evidence Integrity SHA-256**:
\`\`\`text
${evidence.evidenceSha256}
\`\`\`

---

*Generated by Technocore Agent Starter — Contribution Evidence Vault (/evidence)*
`;
}

/**
 * Import and re-verify a raw JSON evidence package.
 * NEVER blindly trusts imported verificationStatus or hashes.
 */
export async function importAndVerifyEvidence(rawJson: string): Promise<EvidenceImportResult> {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawJson);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Invalid JSON";
    return { ok: false, status: "SCHEMA_INVALID", reason: `JSON parse error: ${msg}` };
  }

  let schemaValidated: ContributionEvidenceV1;
  try {
    schemaValidated = validateEvidenceSchema(parsed);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Schema validation error";
    return { ok: false, status: "SCHEMA_INVALID", reason: msg };
  }

  // 1. Re-run Cryptographic Verification over raw fields
  const verification = await verifyEvidenceRecord(
    schemaValidated.room,
    schemaValidated.did,
    schemaValidated.nonce,
    schemaValidated.text,
    schemaValidated.signature,
    schemaValidated.provenance,
  );

  if (!verification.verified) {
    return {
      ok: false,
      status: "SIGNATURE_INVALID",
      evidence: schemaValidated,
      verification,
      reason: `Cryptographic signature mismatch: ${verification.failureReason || "Signature failed Ed25519 verification."}`,
    };
  }

  // 2. Re-compute deterministic integrity hash and compare
  const computedHash = await computeEvidenceIntegrityHash(schemaValidated);
  if (schemaValidated.evidenceSha256 && schemaValidated.evidenceSha256 !== computedHash) {
    return {
      ok: false,
      status: "HASH_MISMATCH",
      evidence: schemaValidated,
      verification: {
        ...verification,
        evidenceSha256: computedHash,
      },
      reason: `Integrity hash mismatch: Stored hash (${schemaValidated.evidenceSha256.slice(0, 12)}...) differs from recomputed canonical hash (${computedHash.slice(0, 12)}...). Data may have been tampered with.`,
    };
  }

  const finalEvidence: ContributionEvidenceV1 = {
    ...schemaValidated,
    verificationStatus: "VERIFIED",
    evidenceSha256: computedHash,
  };

  return {
    ok: true,
    status: "VALID_EVIDENCE",
    evidence: finalEvidence,
    verification: {
      ...verification,
      evidenceSha256: computedHash,
    },
  };
}
